# CircleCI v2.1 Config
version: 2.1

##
# orbs
#
# Orbs used in this pipeline
###
orbs:
  docker: circleci/docker@2.6.0
  slack: circleci/slack@4.12.5 # Ref: https://github.com/mojaloop/ci-config/tree/main/slack-templates

##
# defaults
#
# YAML defaults templates, in alphabetical order
##
defaults_Dependencies: &defaults_Dependencies |
  apk --no-cache add bash
  apk --no-cache add git
  apk --no-cache add ca-certificates
  apk --no-cache add curl
  apk --no-cache add openssh-client
  apk add --no-cache -t build-dependencies make gcc g++ python3 libtool autoconf automake jq
  apk add --no-cache -t openssl ncurses coreutils libgcc linux-headers grep util-linux binutils findutils
  npm install -g node-gyp

defaults_machine_Dependencies: &defaults_machine_Dependencies |
  sudo apt update
  sudo apt install -y docker
  sudo apt install -y docker-compose
  sudo apt install -y musl-dev
  sudo apt install -y build-essential

##
# Executors
#
# CircleCI Executors
##
executors:
  default-docker:
    working_directory: &WORKING_DIR /home/circleci/project/git
    docker:
      - image: node:18-alpine # Ref: https://hub.docker.com/_/node?tab=tags&page=1&name=alpine

  default-machine:
    working_directory: *WORKING_DIR
    machine:
      image: ubuntu-2204:2023.04.2 # Ref: https://circleci.com/developer/machine/image/ubuntu-2204

##
# Jobs
#
# A map of CircleCI jobs
##
jobs:
  Setup:
    executor: default-docker
    steps:
      - run:
          name: Install general dependencies
          command: *defaults_Dependencies
      - checkout
      - run:
          name: Install dependencies (using yarn install)
          command: yarn install --frozen-lockfile
      - run:
          name: Delete build dependencies
          command: apk del build-dependencies
      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  Unit Tests:
    executor: default-docker
    steps:
      - run:
          name: Install general dependencies
          command: *defaults_Dependencies
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Execute unit tests
          command: yarn test
      - store_test_results:
          path: /home/circleci/project/git/
      - store_artifacts:
          path: /home/circleci/project/git/junit.xml

  test-integration:
    executor: default-machine
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-uname -s-uname -m > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Start docker-compose
          command: docker-compose -f docker-compose.yml -f docker-compose.integration.yml up -d
      - run:
          name: Execute integration tests
          command: docker exec -it scheme-adapter-int sh -c 'yarn run test:int'
      - run:
          name: Copy results from docker
          command: docker cp scheme-adapter-int:/junit.xml .
      - store_test_results:
          path: /home/circleci/project/git
      - store_artifacts:
          path: /home/circleci/project/git/junit.xml

  Lint:
    executor: default-docker
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependency-cache-v2-{{ checksum "yarn.lock" }}
      - run:
          name: Execute linting
          command: yarn lint

  # Consolidated License Audit using license-checker
  License Audit:
    executor: default-docker
    steps:
      - checkout
      - run:
          name: Run Yarn license audit
          command: |
            yarn install
            yarn licenses list --json > license-audit-report.json
      - store_artifacts:
          path: ./license-audit-report.json
          destination: license-audit-report.json

  # Vulnerability scan using OWASP Dependency-Check
  Vulnerability Test:
    docker:
    - image: owasp/dependency-check:latest
    steps:
      - checkout
      - run:
          name: Run OWASP Dependency-Check with NVD API Key
          command: |
            /usr/share/dependency-check/bin/dependency-check.sh --project "$CIRCLE_PROJECT_REPONAME" --scan ./ --format "HTML" --out ./dependency-check-report.html --nvdApiKey $NVD_API_KEY
      - store_artifacts:
          path: ./dependency-check-report.html
          destination: dependency-check-report.html

  Build:
    executor: default-machine
    steps:
      - checkout
      - run:
          name: Build Docker local image
          command: |
            echo "Building Docker image: local"
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:local .
      - run:
          name: Save docker image to workspace
          command: docker save -o /tmp/docker-image.tar $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:local
      - persist_to_workspace:
          root: /tmp
          paths:
            - ./docker-image.tar

## Workflows
workflows:
  version: 2
  build_and_test:
    jobs:
      - Setup:
          context: pm4ml-ci
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
                - /hotfix*/
      - Unit Tests:
          context: pm4ml-ci
          requires:
            - Setup
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
                - /hotfix*/
      - Lint:
          context: pm4ml-ci
          requires:
            - Setup
          filters:
            branches:
              ignore:
                - /feature*/
                - /bugfix*/
                - /hotfix*/
      - License Audit:
          context: pm4ml-ci
          requires:
            - Setup
      - Vulnerability Test: 
          context: pm4ml-ci
          requires:
            - Setup
      - Build:
          context: pm4ml-ci
          requires:
            - Lint
            - License Audit
            - Vulnerability Test
