name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]  # Test on multiple Node.js versions

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (required by node-gyp)
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Set up Node.js
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 4: Uninstall node-sass and install sass
      - name: Replace node-sass with sass
        run: |
          npm uninstall node-sass --force
          npm install sass --save-dev --legacy-peer-deps

      # Step 5: Install remaining dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 6: Run the build
      - name: Build the project
        run: npm run build

      # Step 7: Run tests (optional)
      - name: Run tests
        run: npm test
